#!/usr/bin/env python3
"""Generate bundled catalog + progress migration from iOS bundle JSON.

Writes: supabase/migrations/20260412210000_seed_bundled_catalog_and_progress.sql
Run from repo root: python3 supabase/scripts/generate_seed.py
"""

from __future__ import annotations

import json
import pathlib
import uuid

REPO = pathlib.Path(__file__).resolve().parents[2]
NS = uuid.UUID("6f2f1e3a-8c4d-5b6e-9f0a-1b2c3d4e5f60")
MIGRATION = REPO / "supabase/migrations/20260412210000_seed_bundled_catalog_and_progress.sql"


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def sql_opt_str(s):
    if s is None:
        return "null"
    return sql_str(str(s))


def sql_opt_int(n):
    if n is None:
        return "null"
    return str(int(n))


def sql_opt_bool(b):
    if b is None:
        return "null"
    return "true" if b else "false"


def uid(s: str) -> str:
    return str(uuid.uuid5(NS, s))


def main() -> None:
    wp_path = REPO / "bp-workout/Resources/workout_programs.json"
    pd_path = REPO / "bp-workout/Resources/progress_data.json"

    wp = json.loads(wp_path.read_text(encoding="utf-8"))
    programs = wp["programs"]

    by_key: dict[str, str] = {}
    for p in programs:
        for d in p.get("days", []):
            for ex in d.get("exercises", []):
                name = ex.get("name") or ""
                nk = name.strip().lower()
                if nk and nk not in by_key:
                    by_key[nk] = name.strip()

    lines: list[str] = []
    lines.append("-- Bundled catalog + reference progress (from workout_programs.json + progress_data.json).")
    lines.append("-- Generated by supabase/scripts/generate_seed.py — safe to re-run via db reset / db push.")
    lines.append("-- Idempotent upserts (no truncate). After first production deploy, add a new migration for catalog bumps.")
    lines.append("")
    lines.append("begin;")
    lines.append("")
    lines.append("-- exercises")
    for nk in sorted(by_key.keys()):
        name = by_key[nk]
        eid = uid("exercise:" + nk)
        lines.append(
            "insert into public.exercises (id, name, name_key) values "
            f"({sql_str(eid)}::uuid, {sql_str(name)}, {sql_str(nk)}) "
            "on conflict (name_key) do update set name = excluded.name;"
        )
    lines.append("")
    lines.append("-- catalog programs + days + lines")
    for p in programs:
        pid = p["id"]
        lines.append(
            "insert into public.catalog_programs (id, name, subtitle, period, date_range, color, is_user_created) values ("
            f"{sql_str(pid)}, {sql_str(p.get('name', ''))}, {sql_str(p.get('subtitle', ''))}, "
            f"{sql_str(p.get('period', ''))}, {sql_str(p.get('dateRange', ''))}, {sql_str(p.get('color', '#66bfcc'))}, "
            f"{'true' if p.get('isUserCreated') else 'false'}"
            ") on conflict (id) do update set "
            "name = excluded.name, subtitle = excluded.subtitle, period = excluded.period, "
            "date_range = excluded.date_range, color = excluded.color, is_user_created = excluded.is_user_created;"
        )
        for di, day in enumerate(p.get("days", [])):
            did = uid(f"day:{pid}:{di}")
            lines.append(
                "insert into public.catalog_program_days (id, program_id, day_index, label) values ("
                f"{sql_str(did)}::uuid, {sql_str(pid)}, {di}, {sql_str(day.get('label', ''))}) "
                "on conflict (program_id, day_index) do update set label = excluded.label;"
            )
            for ei, ex in enumerate(day.get("exercises", [])):
                nk = (ex.get("name") or "").strip().lower()
                eid = uid("exercise:" + nk)
                lines.append(
                    "insert into public.catalog_day_exercises (program_day_id, exercise_id, sort_order, max_weight, target_sets, superset_group, is_amrap, is_warmup, notes) values ("
                    f"{sql_str(did)}::uuid, {sql_str(eid)}::uuid, {ei}, "
                    f"{sql_str(ex.get('maxWeight', ''))}, {sql_opt_int(ex.get('targetSets'))}, "
                    f"{sql_opt_int(ex.get('supersetGroup'))}, {sql_opt_bool(ex.get('isAmrap'))}, "
                    f"{sql_opt_bool(ex.get('isWarmup'))}, {sql_opt_str(ex.get('notes'))}) "
                    "on conflict (program_day_id, sort_order) do update set "
                    "exercise_id = excluded.exercise_id, max_weight = excluded.max_weight, "
                    "target_sets = excluded.target_sets, superset_group = excluded.superset_group, "
                    "is_amrap = excluded.is_amrap, is_warmup = excluded.is_warmup, notes = excluded.notes;"
                )
    lines.append("")
    lines.append("insert into public.catalog_release (id, version, notes, published_at)")
    lines.append("values (1, 1, 'migration: workout_programs.json', now())")
    lines.append("on conflict (id) do update set")
    lines.append("  version = 1,")
    lines.append("  notes = excluded.notes,")
    lines.append("  published_at = excluded.published_at;")
    lines.append("")

    pd = json.loads(pd_path.read_text(encoding="utf-8"))
    assert "exerciseProgressData" in pd and "programColors" in pd
    raw = json.dumps(pd, separators=(",", ":"))
    tag = "progress_json"
    if tag in raw:
        tag = "progress_data_body"

    lines.append("insert into public.bundled_progress_reference (id, payload)")
    lines.append(f"values (1, ${tag}${raw}${tag}$::jsonb)")
    lines.append("on conflict (id) do update set")
    lines.append("  payload = excluded.payload,")
    lines.append("  updated_at = now();")
    lines.append("")
    lines.append("commit;")

    MIGRATION.parent.mkdir(parents=True, exist_ok=True)
    MIGRATION.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {MIGRATION} ({MIGRATION.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
